export interface PropSchema {
  type: string;
  default: unknown;
}

export interface ComponentSchema {
  displayName: string;
  props: Record<string, PropSchema>;
}

export const COMPONENT_SCHEMAS: Record<string, ComponentSchema> = {
  CraftDiv: {
    displayName: "Div",
    props: {
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftImage: {
    displayName: "Image",
    props: {
      src: { type: "string", default: "" },
      alt: { type: "string", default: "" },
      width: { type: "string", default: "300px" },
      height: { type: "string", default: "200px" },
      objectFit: { type: "cover|contain|fill|none|scale-down", default: "cover" },
      keepAspectRatio: { type: "boolean", default: false },
      className: { type: "string", default: "" },
    },
  },
  CraftPlaceholderImage: {
    displayName: "Placeholder Image",
    props: {
      src: { type: "string", default: "https://placehold.co/300x200/e2e8f0/64748b?text=Image" },
      alt: { type: "string", default: "Placeholder" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      keepAspectRatio: { type: "boolean", default: false },
      className: { type: "string", default: "" },
    },
  },
  CraftText: {
    displayName: "Text",
    props: {
      text: { type: "string", default: "Text" },
      tag: { type: "p|span|h1|h2|h3|h4|h5|h6", default: "p" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftContainer: {
    displayName: "Container",
    props: {
      display: { type: "flex|grid", default: "flex" },
      flexDirection: { type: "row|column", default: "row" },
      gap: { type: "0|1|2|3|4|5|6|8|10|12|16|20|24", default: "4" },
      gridCols: { type: "number", default: 3 },
      linkedMocPath: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftFreeCanvas: {
    displayName: "Free Canvas",
    props: {
      width: { type: "string", default: "100%" },
      height: { type: "string", default: "100vh" },
      className: { type: "string", default: "" },
    },
  },
  CraftAccordion: {
    displayName: "Accordion",
    props: {
      items: { type: "string", default: "Item 1,Item 2,Item 3" },
      type: { type: "single|multiple", default: "single" },
      linkedMocPaths: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftAlert: {
    displayName: "Alert",
    props: {
      title: { type: "string", default: "Alert" },
      description: { type: "string", default: "This is an alert message." },
      variant: { type: "default|destructive", default: "default" },
      icon: { type: "string", default: "AlertCircle" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftAspectRatio: {
    displayName: "AspectRatio",
    props: {
      ratio: { type: "number", default: 1.7778 },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      keepAspectRatio: { type: "boolean", default: true },
      className: { type: "string", default: "" },
    },
  },
  CraftAvatar: {
    displayName: "Avatar",
    props: {
      src: { type: "string", default: "" },
      fallback: { type: "string", default: "AB" },
      size: { type: "default|sm|lg", default: "default" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftBadge: {
    displayName: "Badge",
    props: {
      text: { type: "string", default: "Badge" },
      variant: { type: "default|secondary|destructive|outline", default: "default" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftBreadcrumb: {
    displayName: "Breadcrumb",
    props: {
      items: { type: "string", default: "Home,Products,Current" },
      maxVisible: { type: "string", default: "0" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftButton: {
    displayName: "Button",
    props: {
      text: { type: "string", default: "Button" },
      variant: { type: "default|destructive|outline|secondary|ghost|link", default: "default" },
      size: { type: "default|sm|lg|icon", default: "default" },
      disabled: { type: "boolean", default: false },
      overlayType: { type: "none|dialog|alert-dialog|sheet|drawer|popover|dropdown-menu", default: "none" },
      linkedMocPath: { type: "string", default: "" },
      sheetSide: { type: "top|right|bottom|left", default: "right" },
      alertDialogPattern: { type: "cancel-continue|continue-cancel|yes-no|no-yes|ok-cancel|cancel-ok", default: "cancel-continue" },
      overlayWidth: { type: "string", default: "" },
      overlayHeight: { type: "string", default: "" },
      overlayClassName: { type: "string", default: "" },
      tooltipText: { type: "string", default: "" },
      tooltipSide: { type: "|top|right|bottom|left", default: "" },
      toastText: { type: "string", default: "" },
      toastPosition: { type: "bottom-right|bottom-left|top-right|top-left", default: "bottom-right" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftButtonGroup: {
    displayName: "ButtonGroup",
    props: {
      orientation: { type: "horizontal|vertical", default: "horizontal" },
      variant: { type: "default|destructive|outline|secondary|ghost|link", default: "outline" },
      size: { type: "default|sm|lg|icon", default: "default" },
      buttonData: { type: "JSON string", default: "(JSON)" },
      tooltipText: { type: "string", default: "" },
      tooltipSide: { type: "|top|right|bottom|left", default: "" },
      tooltipTrigger: { type: "hover|focus", default: "hover" },
      hoverCardMocPath: { type: "string", default: "" },
      hoverCardSide: { type: "top|right|bottom|left", default: "bottom" },
      hoverCardTrigger: { type: "hover|focus", default: "hover" },
      contextMenuMocPath: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftCalendar: {
    displayName: "Calendar",
    props: {
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
      todayBgClass: { type: "string", default: "" },
      todayTextClass: { type: "string", default: "" },
    },
  },
  CraftCard: {
    displayName: "Card",
    props: {
      title: { type: "string", default: "Card Title" },
      description: { type: "string", default: "" },
      contextMenuMocPath: { type: "string", default: "" },
      linkedMocPath: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftCarousel: {
    displayName: "Carousel",
    props: {
      slideMeta: { type: "JSON string", default: "(JSON)" },
      orientation: { type: "horizontal|vertical", default: "horizontal" },
      loop: { type: "boolean", default: false },
      showArrows: { type: "boolean", default: true },
      width: { type: "string", default: "320px" },
      height: { type: "string", default: "200px" },
      className: { type: "string", default: "" },
    },
  },
  CraftCheckbox: {
    displayName: "Checkbox",
    props: {
      label: { type: "string", default: "Accept terms" },
      checked: { type: "boolean", default: false },
      disabled: { type: "boolean", default: false },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftCollapsible: {
    displayName: "Collapsible",
    props: {
      open: { type: "boolean", default: false },
      triggerStyle: { type: "chevron|plus-minus|arrow|none", default: "chevron" },
      linkedMocPath: { type: "string", default: "" },
      outerBorderColor: { type: "string", default: "" },
      dividerBorderColor: { type: "string", default: "" },
      triggerBorderColor: { type: "string", default: "" },
      outerShadow: { type: "string", default: "" },
      contentShadow: { type: "string", default: "" },
      triggerShadow: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftCombobox: {
    displayName: "Combobox",
    props: {
      items: { type: "string", default: "Apple,Banana,Cherry" },
      placeholder: { type: "string", default: "Select an option..." },
      linkedMocPath: { type: "string", default: "" },
      contentWidth: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftCommand: {
    displayName: "Command",
    props: {
      commandData: { type: "JSON string", default: "(JSON)" },
      placeholder: { type: "string", default: "Type a command or search..." },
      itemBgClass: { type: "string", default: "" },
      itemTextClass: { type: "string", default: "" },
      itemBorderClass: { type: "string", default: "" },
      itemBorderWidth: { type: "string", default: "" },
      itemShadowClass: { type: "string", default: "" },
      hoverBgClass: { type: "string", default: "" },
      hoverTextClass: { type: "string", default: "" },
      iconClass: { type: "string", default: "" },
      shortcutTextClass: { type: "string", default: "" },
      groupHeadingClass: { type: "string", default: "" },
      inputBorderClass: { type: "string", default: "" },
      inputBorderWidth: { type: "string", default: "" },
      inputRoundedClass: { type: "string", default: "" },
      separatorClass: { type: "string", default: "" },
      separatorShadowClass: { type: "string", default: "" },
      separatorBorderClass: { type: "string", default: "" },
      separatorBorderWidth: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftContextMenu: {
    displayName: "ContextMenu",
    props: {
      menuData: { type: "JSON string", default: "(JSON)" },
      panelBgClass: { type: "string", default: "" },
      panelTextClass: { type: "string", default: "" },
      panelBorderClass: { type: "string", default: "" },
      panelBorderWidth: { type: "string", default: "" },
      panelShadowClass: { type: "string", default: "" },
      hoverBgClass: { type: "string", default: "" },
      hoverTextClass: { type: "string", default: "" },
      shortcutTextClass: { type: "string", default: "" },
      checkTextClass: { type: "string", default: "" },
      width: { type: "string", default: "200px" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftDataTable: {
    displayName: "Data Table",
    props: {
      columnDefs: { type: "JSON string", default: "(JSON)" },
      csvData: { type: "CSV string", default: "(CSV)" },
      filterType: { type: "none|header|bar", default: "none" },
      pageable: { type: "boolean", default: false },
      pageSize: { type: "string", default: "10" },
      selectable: { type: "boolean", default: false },
      columnToggle: { type: "boolean", default: false },
      stickyHeader: { type: "boolean", default: false },
      pinnedLeft: { type: "string", default: "0" },
      headerBgClass: { type: "string", default: "" },
      hoverRowClass: { type: "string", default: "" },
      selectedRowClass: { type: "string", default: "" },
      headerTextClass: { type: "string", default: "" },
      headerHoverTextClass: { type: "string", default: "" },
      headerBorderClass: { type: "string", default: "" },
      tableBorderClass: { type: "string", default: "" },
      sortIconClass: { type: "string", default: "" },
      filterIconClass: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftDatePicker: {
    displayName: "DatePicker",
    props: {
      mode: { type: "date|datetime", default: "date" },
      dateFormat: { type: "string", default: "yyyy/MM/dd" },
      placeholder: { type: "string", default: "日付を選択..." },
      editable: { type: "boolean", default: false },
      disabled: { type: "boolean", default: false },
      calendarBorderClass: { type: "string", default: "" },
      calendarShadowClass: { type: "string", default: "" },
      todayBgClass: { type: "string", default: "" },
      todayTextClass: { type: "string", default: "" },
      todayBorderClass: { type: "string", default: "" },
      todayShadowClass: { type: "string", default: "" },
      selectedBgClass: { type: "string", default: "" },
      selectedTextClass: { type: "string", default: "" },
      selectedBorderClass: { type: "string", default: "" },
      selectedShadowClass: { type: "string", default: "" },
      buttonBgClass: { type: "string", default: "" },
      hoverBgClass: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftDropdownMenu: {
    displayName: "DropdownMenu",
    props: {
      triggerText: { type: "string", default: "Open Menu" },
      menuData: { type: "JSON string", default: "(JSON)" },
      triggerBgClass: { type: "string", default: "" },
      triggerTextClass: { type: "string", default: "" },
      triggerBorderClass: { type: "string", default: "" },
      triggerBorderWidth: { type: "string", default: "" },
      triggerShadowClass: { type: "string", default: "" },
      dropdownBgClass: { type: "string", default: "" },
      dropdownTextClass: { type: "string", default: "" },
      dropdownBorderClass: { type: "string", default: "" },
      dropdownBorderWidth: { type: "string", default: "" },
      dropdownShadowClass: { type: "string", default: "" },
      dropdownWidth: { type: "string", default: "" },
      hoverBgClass: { type: "string", default: "" },
      hoverTextClass: { type: "string", default: "" },
      shortcutTextClass: { type: "string", default: "" },
      checkTextClass: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftHoverCard: {
    displayName: "HoverCard",
    props: {
      triggerText: { type: "string", default: "Hover me" },
      linkedMocPath: { type: "string", default: "" },
      cardBorderClass: { type: "string", default: "" },
      cardBorderWidth: { type: "string", default: "" },
      cardShadowClass: { type: "string", default: "" },
      cardBorderRadius: { type: "string", default: "rounded-md" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftInput: {
    displayName: "Input",
    props: {
      type: { type: "text|email|password|number|tel|url|search", default: "text" },
      placeholder: { type: "string", default: "Enter text..." },
      disabled: { type: "boolean", default: false },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftKbd: {
    displayName: "Kbd",
    props: {
      keys: { type: "string", default: "⌘+K" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftLabel: {
    displayName: "Label",
    props: {
      text: { type: "string", default: "Label" },
      htmlFor: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftMenubar: {
    displayName: "Menubar",
    props: {
      menuData: { type: "JSON string", default: "(JSON)" },
      buttonBgClass: { type: "string", default: "" },
      buttonTextClass: { type: "string", default: "" },
      buttonBorderClass: { type: "string", default: "" },
      buttonBorderWidth: { type: "string", default: "" },
      buttonShadowClass: { type: "string", default: "" },
      hoverBgClass: { type: "string", default: "" },
      hoverTextClass: { type: "string", default: "" },
      dropdownBgClass: { type: "string", default: "" },
      dropdownTextClass: { type: "string", default: "" },
      dropdownBorderClass: { type: "string", default: "" },
      dropdownBorderWidth: { type: "string", default: "" },
      dropdownShadowClass: { type: "string", default: "" },
      dropdownWidth: { type: "string", default: "" },
      shortcutTextClass: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftNavigationMenu: {
    displayName: "Navigation Menu",
    props: {
      items: { type: "string", default: "Getting Started,Components,Documentation" },
      buttonBgClass: { type: "string", default: "" },
      hoverBgClass: { type: "string", default: "" },
      hoverTextClass: { type: "string", default: "" },
      buttonBorderClass: { type: "string", default: "" },
      buttonBorderWidth: { type: "string", default: "" },
      buttonShadowClass: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftPagination: {
    displayName: "Pagination",
    props: {
      totalPages: { type: "number", default: 5 },
      currentPage: { type: "number", default: 1 },
      hoverBgClass: { type: "string", default: "" },
      hoverTextClass: { type: "string", default: "" },
      activeBgClass: { type: "string", default: "" },
      activeTextClass: { type: "string", default: "" },
      activeBorderClass: { type: "string", default: "" },
      activeBorderWidth: { type: "string", default: "" },
      activeShadowClass: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftProgress: {
    displayName: "Progress",
    props: {
      value: { type: "number", default: 50 },
      indicatorClass: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftRadioGroup: {
    displayName: "RadioGroup",
    props: {
      items: { type: "string", default: "Option A,Option B,Option C" },
      value: { type: "string", default: "Option A" },
      orientation: { type: "vertical|horizontal", default: "vertical" },
      variant: { type: "default|card", default: "default" },
      descriptions: { type: "string", default: "" },
      cardBorderColor: { type: "string", default: "" },
      cardBgColor: { type: "string", default: "" },
      descriptionColor: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftResizable: {
    displayName: "Resizable",
    props: {
      panelMeta: { type: "JSON string", default: "(JSON)" },
      withHandle: { type: "boolean", default: true },
      borderColor: { type: "string", default: "" },
      separatorColor: { type: "string", default: "" },
      separatorSize: { type: "string", default: "4" },
      borderRadius: { type: "string", default: "rounded-lg" },
      shadow: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "200px" },
      className: { type: "string", default: "" },
    },
  },
  CraftScrollArea: {
    displayName: "ScrollArea",
    props: {
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "200px" },
      className: { type: "string", default: "" },
    },
  },
  CraftSelect: {
    displayName: "Select",
    props: {
      items: { type: "string", default: "Option 1,Option 2,Option 3" },
      placeholder: { type: "string", default: "Select an option" },
      contentWidth: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftSeparator: {
    displayName: "Separator",
    props: {
      orientation: { type: "horizontal|vertical", default: "horizontal" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftSidebar: {
    displayName: "Sidebar",
    props: {
      sidebarData: { type: "JSON string", default: "(JSON)" },
      side: { type: "left|right", default: "left" },
      collapsible: { type: "icon|offcanvas|none", default: "icon" },
      sidebarWidth: { type: "string", default: "240px" },
      headerCollapseMode: { type: "clip|hide", default: "clip" },
      footerCollapseMode: { type: "clip|hide", default: "clip" },
      sidebarBgClass: { type: "string", default: "" },
      sidebarBorderColor: { type: "string", default: "" },
      sidebarShadow: { type: "string", default: "" },
      headerBgClass: { type: "string", default: "" },
      headerBorderColor: { type: "string", default: "" },
      headerShadow: { type: "string", default: "" },
      navActiveBgClass: { type: "string", default: "" },
      navHoverBgClass: { type: "string", default: "" },
      navTextClass: { type: "string", default: "" },
      navIconClass: { type: "string", default: "" },
      footerBgClass: { type: "string", default: "" },
      footerBorderColor: { type: "string", default: "" },
      footerShadow: { type: "string", default: "" },
      insetBgClass: { type: "string", default: "" },
      insetBorderColor: { type: "string", default: "" },
      insetShadow: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftSlider: {
    displayName: "Slider",
    props: {
      value: { type: "number", default: 50 },
      min: { type: "number", default: 0 },
      max: { type: "number", default: 100 },
      step: { type: "number", default: 1 },
      fillClassName: { type: "string", default: "" },
      trackClassName: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftSwitch: {
    displayName: "Switch",
    props: {
      label: { type: "string", default: "Toggle" },
      checked: { type: "boolean", default: false },
      disabled: { type: "boolean", default: false },
      description: { type: "string", default: "" },
      invalid: { type: "boolean", default: false },
      size: { type: "default|sm", default: "default" },
      variant: { type: "default|card", default: "default" },
      checkedClassName: { type: "string", default: "" },
      uncheckedClassName: { type: "string", default: "" },
      cardBorderColor: { type: "string", default: "" },
      cardBgColor: { type: "string", default: "" },
      descriptionColor: { type: "string", default: "" },
      labelColor: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftTable: {
    displayName: "Table",
    props: {
      tableMeta: { type: "JSON string", default: "(JSON)" },
      borderColor: { type: "string", default: "" },
      borderWidth: { type: "string", default: "1" },
      stickyHeader: { type: "string", default: "" },
      pinnedLeft: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftTabs: {
    displayName: "Tabs",
    props: {
      tabMeta: { type: "JSON string", default: "(JSON)" },
      orientation: { type: "horizontal|vertical", default: "horizontal" },
      tabButtonWidth: { type: "string", default: "auto" },
      tabListBgClass: { type: "string", default: "" },
      tabActiveBgClass: { type: "string", default: "" },
      contentBgClass: { type: "string", default: "" },
      outerBorderColor: { type: "string", default: "" },
      contentBorderColor: { type: "string", default: "" },
      outerShadow: { type: "string", default: "" },
      contentShadow: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftTextarea: {
    displayName: "Textarea",
    props: {
      placeholder: { type: "string", default: "Type your message here." },
      rows: { type: "number", default: 3 },
      disabled: { type: "boolean", default: false },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftToggle: {
    displayName: "Toggle",
    props: {
      text: { type: "string", default: "Toggle" },
      variant: { type: "default|outline", default: "default" },
      size: { type: "default|sm|lg", default: "default" },
      pressed: { type: "boolean", default: false },
      disabled: { type: "boolean", default: false },
      icon: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftToggleGroup: {
    displayName: "ToggleGroup",
    props: {
      items: { type: "string", default: "Bold,Italic,Underline" },
      type: { type: "single|multiple", default: "single" },
      variant: { type: "default|outline", default: "default" },
      size: { type: "default|sm|lg", default: "default" },
      disabled: { type: "boolean", default: false },
      gap: { type: "0|1|2|3|4|6|8", default: "1" },
      orientation: { type: "horizontal|vertical", default: "horizontal" },
      descriptions: { type: "string", default: "" },
      cardBorderColor: { type: "string", default: "" },
      cardBgColor: { type: "string", default: "" },
      descriptionColor: { type: "string", default: "" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftTooltip: {
    displayName: "Tooltip",
    props: {
      triggerText: { type: "string", default: "Hover" },
      text: { type: "string", default: "Tooltip text" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
  CraftTypography: {
    displayName: "Typography",
    props: {
      variant: { type: "h1|h2|h3|h4|p|blockquote|ul|ol|code|lead|large|small|muted", default: "h1" },
      text: { type: "string", default: "Heading 1" },
      items: { type: "string", default: "List item 1,List item 2,List item 3" },
      width: { type: "string", default: "auto" },
      height: { type: "string", default: "auto" },
      className: { type: "string", default: "" },
    },
  },
};

/** スロットコンポーネントとして @moc-component タグ出力から除外するコンポーネント名 */
export const SLOT_COMPONENT_NAMES = new Set([
  "CollapsibleSlot",
  "DataTableSlot",
  "NavMenuSlot",
  "ResizablePanelSlot",
  "SidebarFooterSlot",
  "SidebarHeaderSlot",
  "SidebarInsetSlot",
  "SlideContentSlot",
  "TableCellSlot",
  "TabContentSlot",
]);
